---
title: "EX4-ML"
author: "AdamAndDaniel"
date: "June 9, 2016"
output: pdf document
---
##### EX4 - ML
```{r setup, include=FALSE}
rm(list = ls(all = TRUE))

library(stringdist)
library(readr)
library(caret)
library(randomForest)
library(tm)   
library(SnowballC)  
Sys.setlocale("LC_ALL", "C")
```



```{r}
test  <- read_csv(file="dataFiles/test.csv")
train <- read_csv(file="dataFiles/train.csv")

doc_product_title <- VCorpus(VectorSource(test$product_title),readerControl = list(language = "lat"))
doc_product_desc <- VCorpus(VectorSource(test$product_description),readerControl = list(language = "lat")) 

```

```{r echo=TRUE}
writeLines(as.character(clean_doc_product_title[[5]]))
writeLines(as.character(doc_product_title[[5]]))
```

##### Tranform to lower
```{r}
clean_doc_product_title <- tm_map(doc_product_title, content_transformer(tolower))
clean_doc_product_desc <- tm_map(doc_product_desc, content_transformer(tolower))
```
##### Punctation
```{r}
clean_doc_product_title <- tm_map(doc_product_title, removePunctuation)
clean_doc_product_desc <- tm_map(doc_product_desc, removePunctuation)

```
##### Removing “stopwords” 
```{r}
clean_doc_product_title <- tm_map(clean_doc_product_title, removeWords, stopwords("english"))   
clean_doc_product_desc <- tm_map(clean_doc_product_desc, removeWords, stopwords("english"))   
```

##### Preparing data frame to insert the clean test data aftr prep
```{r}
clean_test <- as.data.frame(matrix(nrow = 1,ncol=3))
clean_test_dec <- as.data.frame(matrix(nrow = 1,ncol=1))
colnames(clean_test) <- c("id","query","product_title")
colnames(clean_test_dec) <- c("product_description")
```

##### two loops to extract data 
```{r}
for(i in 1:length(clean_doc_product_title)) {
  id <- test[i,1]
  query <- test[i,2]
  title <-as.character(clean_doc_product_title[[i]])
  row <- c(id = as.integer(id), query = as.String(query),product_title = as.String(title),product_description = "")  
  clean_test <- rbind(clean_test,row)
}

for(i in 1:length(clean_doc_product_desc)) {
  desc <-as.character(clean_doc_product_desc[[i]])
  clean_test_dec <- rbind(clean_test_dec,desc)
}
```

```{r}
clean_test <- as.data.frame(na.omit(clean_test))
clean_test_dec <- as.data.frame(na.omit(clean_test_dec))

clean_test <- cbind(clean_test,clean_test_dec)
```

```{r echo=TRUE}
summary(round(stringdist(train$query,train$product_title,method = "jw"),4))
```
#Jaro-Winker distance - jw 

```{r}
train$jw_dist_title <- stringdist(train$query,train$product_title,method = "jw") 
train$jw_dist_desc <- stringdist(train$query,train$product_description,method = "jw") 

test$jw_dist_title <- stringdist(clean_test$query,clean_test$product_title,method = "jw") 
test$jw_dist_desc <- stringdist(clean_test$query,clean_test$product_description,method = "jw") 

train$median_relevance <- as.factor(train$median_relevance)
```

#Model Building

```{r}

model_formula_jw <- as.formula(median_relevance ~ jw_dist_title + jw_dist_desc )
model_rf <- randomForest(formula = model_formula_jw,data = train,ntree = 500, method="class")

```

#Prediction on test

```{r}

prediction <- predict(model_rf,test[,c(5,6)])
submit <- data.frame(cbind(clean_test$id,prediction))
colnames(submit) <- c("id", "prediction")
write.csv(submit,"submission_jw_pp.csv", row.names=FALSE)
```




